### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by ialkamal** [grubersjoe/react-github-calendar#24]
Hi, I was using the react component and the api suddenly went down today.

Error on my end:
"Access to fetch at 'https://github-calendar.now.sh/v1/timelyportfolio' from origin 'https://happy-volhard-67ac11.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

**Comment by aashutoshrathi** [comment]
+1 
Facing same

**Comment by grubersjoe** [comment]
Thanks for pointing this out. It was already broken on the 28th because GitHub changed their HTML output in the contribution graph. Now they changed the colors again as a Halloween Easter egg. Unfortunately, the API providing the contribution data to this React component is not very robust in this regard. When the colors change (I assumed they do very rarely) the API is unable to map colors to a contribution "intensity". GitHub uses CSS variables since a few days to style the block colors which sounds sounds, because you could think that the variable names should stay the same. However, right now they use different variable names because of Halloween. So in conclusion there is not much to do here, but to wait one day, I guess. 

I have added a check to the API so that it will return a HTTP 500 and a more verbose error message like the following when things break, however:

>  Scraping profile of grubersjoe has failed: Unable to retrieve contribution data per day. Please open an issue here: https://github.com/grubersjoe/react-github-calendar/issues.

I'm going to show these error messages in the React component instead of simply returning "Error :(".

**Comment by ialkamal** [comment]
Thanks @grubersjoe, resolved and back to normal!
