### ISSUE TITLE
theme function not working in react

### ISSUE THREAD

**Issue by Newgin-sam** [grubersjoe/react-github-calendar#28]
when i'm trying to use theme what ever color i give i get dark blue color.

   ```
 const colorTheme = {
        "background": 'transparent',
        "text": '#ffffff',
        "grade4": '#161b1bda',
        "grade3": '#0094d8da',
        "grade2": '#00e0f0d1',
        "grade1": '#98d9e9ce',
        "grade0": '#ffffffce',
    };
    
    <GitHubCalendar username="newgin-sam" blockSize={20}
           blockMargin={5}
          theme={colorTheme}
          fontSize={15}
      />
```

this is the code i used

and this is the output

![image](https://user-images.githubusercontent.com/60768808/130443622-b41aab49-da97-4309-b5db-71b60c57e3cb.png)

**Comment by grubersjoe** [comment]
Hey. What version of `react-github-calendar` are you using? Above theme object is in the format that was requried for v2. If you should use `react-github-calendar` 3.x then this will no longer work, because theme format has changed (breaking change).

When using v2 it works:
![image](https://user-images.githubusercontent.com/3109364/130449444-504cd3aa-3007-4715-8957-524a25f33993.png)

See documentation how to upgarde to v3:
https://grubersjoe.github.io/react-github-calendar/#upgrade

With v3 it should look like this:

```js
const colorTheme = {
     "level4": '#161b1bda',
     "level3": '#0094d8da',
     "level2": '#00e0f0d1',
     "level1": '#98d9e9ce',
     "level0": '#ffffffce',
 };
 ```

**Comment by Newgin-sam** [comment]
thanks @grubersjoe 

the below color theme is working for 

> "react-github-calendar": "^2.0.2"

```
const colorTheme = {
  "level4": '#161b1bda',
  "level3": '#0094d8da',
  "level2": '#00e0f0d1',
  "level1": '#98d9e9ce',
  "level0": '#ffffffce',
 };

```
