### ISSUE TITLE
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by gujiwuqing** [grubersjoe/react-github-calendar#36]
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/44566835/157450340-a9fc928e-1ec3-43c9-afdd-92ac72ed2ff0.png">
I don't know what the problem is, I want to ask how to solve it

**Comment by grubersjoe** [comment]
Hey. The issue is that Webpack (I suppose it's integrated in the build process of UmiJS?) is trying to load the ESM module (`index.es.js`) and has no handler configured for this format as it states. I am aware that ESM modules are not widely supported yet and therefore this package also provides a CommonJS build:

```
// package.json
"main": "dist/index.js", // CommonJS
"module": "dist/index.es.js", // ESM
```

So far I had no complaints with this approach. In theory bundlers that support ESM should pick `dist/index.es.js` and those that don't should use `dist/index.js`. More about this "hybrid" approach: https://2ality.com/2019/10/hybrid-npm-packages.html.

So I think you need to configure your bundler to either choose the correct file or enhance its configuration to support ESM modules.

**Comment by gujiwuqing** [comment]
> Hey. The issue is that Webpack (I suppose it's integrated in the build process of UmiJS?) is trying to load the ESM module (`index.es.js`) and has no handler configured for this format as it states. I am aware that ESM modules are not widely supported yet and therefore this package also provides a CommonJS build:
> 
> ```
> // package.json
> "main": "dist/index.js", // CommonJS
> "module": "dist/index.es.js", // ESM
> ```
> 
> So far I had no complaints with this approach. In theory bundlers that support ESM should pick `dist/index.es.js` and those that don't should use `dist/index.js`. More about this "hybrid" approach: https://2ality.com/2019/10/hybrid-npm-packages.html.
> 
> So I think you need to configure your bundler to either choose the correct file or enhance its configuration to support ESM modules.

Thanks a lot, I'll try it

**Comment by grubersjoe** [comment]
You know what... I thought about it and currently there does not seem to be a huge advantage of having ESM at all. So I ditched ESM and only provide CommonJS. Can you try `react-github-calendar@3.3.0` in your app again? This should hopefully simply work.

**Comment by gujiwuqing** [comment]
> 
yes  i can thank you

**Comment by grubersjoe** [comment]
I'll assume this is fixed then.

**Comment by CallumJHays** [comment]
Hi, I just ran into this as well.
I was using nextjs@10 for my webpack config.
I fixed it by upgrading to next@12
