### ISSUE TITLE
Cannot remove borders in contribution graph

### ISSUE THREAD

**Issue by shrihari-prakash** [grubersjoe/react-github-calendar#46]
Is there an option that controls the default borders in the graph? Currently there is a subtle border applied on all tiles:

![image](https://user-images.githubusercontent.com/35889246/223623321-2aa3d88d-907c-4bae-b61b-de072a67cb8c.png)

**Comment by grubersjoe** [comment]
Hey. There's no property for that, but you can easily hide borders with a little bit of CSS:

```css
.react-activity-calendar rect {
  stroke: none;
}
```

I saw on your page that you used a similar approach. Though, I would recommend not to use `*` as selector, because then the `stroke` of _all_ SVG elements on the page will disappear. Also `!important` is not really necessary.

**Comment by shrihari-prakash** [comment]
Hey man, thanks for the quick revert. Agree that using `*` is a bad practice 🙂. I just changed it to the one you suggested and it works perfectly. I was trying the same yesterday and for some reason it didn't work lol.
