### ISSUE TITLE
certain usernames throw error that crash app

### ISSUE THREAD

**Issue by kyle-richardson** [grubersjoe/react-github-calendar#5]
"Can't perform a React state update on an unmounted component" is thrown when using specific usernames, seemingly.  The only one I found was my own, "kyle-richardson".  Cannot figure out why it fails, tested with other usernames that have hyphens in them and they work.  Also cannot find any other username yet that fails to work.  unsure as yet why mine is having the specific issue.

**Comment by grubersjoe** [comment]
Hey. This was a bug in my code (actually I even found another one while checking this out). The problem was, that my code naively assumed that there's data for at least one year, which of course is not necessarily the case.

Thank's for the feedback, I have fixed both issues now. Please try again :).

**Comment by kyle-richardson** [comment]
thanks worked!
