### ISSUE TITLE
bounded to next js

### ISSUE THREAD

**Issue by broisnischal** [grubersjoe/react-github-calendar#66]
getting error while using in other library like, remix, svelte and other.

**Comment by grubersjoe** [comment]
What's the error? Are you on the latest version?

**Comment by broisnischal** [comment]
yep, I am in the latest version if i try that component in remix, i can't cause it is bounded to next js/react, can you help me for my project ?

**Comment by broisnischal** [comment]
Hey can we connect via twitter for little meetup if you don't mind i have contacted you in your twitter!?

**Comment by grubersjoe** [comment]
I'd like to keep this discussion here.

Tried it out in Next.js yesterday and it worked fine, but I agree that something is off in Remix. I see a different error though:

Next.js:
<img width="927" alt="image" src="https://github.com/grubersjoe/react-github-calendar/assets/3109364/91c8b8e6-b838-4adc-ad98-63d2ab6f7a3e">

Remix:
<img width="1158" alt="image" src="https://github.com/grubersjoe/react-github-calendar/assets/3109364/6db2c7a5-d182-4c6d-aae1-6ad5702be960">

**Comment by ejscheepers** [comment]
I also got this error in Astro:

<img width="1274" alt="Screenshot 2024-08-03 at 14 31 32" src="https://github.com/user-attachments/assets/3e73803d-4888-44df-bd42-863a47125c77">

Any solutions yet @grubersjoe ?

**Comment by grubersjoe** [comment]
None yet, but I'll try to work on this soon

**Comment by grubersjoe** [comment]
So the issue at least for Remix seems to be the one described in this [discussion](https://github.com/remix-run/remix/discussions/8686). This component cannot be rendered on the server because it uses client hooks and relies on browser APIs. The calendar component checks this and will [return `null` on the server](https://github.com/grubersjoe/react-activity-calendar/blob/main/src/index.tsx).

However, even if you use `.client` modules in Remix the parent component where the client component is used is still rendered on the server. According to Remix docs the client module resolves there to `{}` and consequently you get above error.

https://remix.run/docs/en/main/file-conventions/-client

> Note that values exported from this module will all be undefined on the server, so the only places to use them are in [useEffect](https://react.dev/reference/react/useEffect) and user events like click handlers.

There are [various](https://github.com/remix-run/remix/issues/8378) [issues](https://github.com/remix-run/remix/issues/8691) about this in Remix repo. They all boil down to either use [`<ClientOnly>`](https://github.com/sergiodxa/remix-utils?tab=readme-ov-file#clientonly) from remix-utils to enforce rendering on the client only or to check for this yourself:

```tsx
import {useEffect, useState} from "react";
import ActivityCalendar from "react-activity-calendar";

export default function Calendar() {
    const [isClient, setIsClient] = useState(false)

    useEffect(() => {
        setIsClient(true)
    }, []);

    const data = [
        {
            date: "2023-06-01",
            count: 2,
            level: 1,
        },
        {
            date: "2023-09-01",
            count: 16,
            level: 3,
        },
    ];

    return isClient && <ActivityCalendar data={data} />
}
```

**Comment by grubersjoe** [comment]
Checked Next.js, it renders fine there without some extra client checks.

**Comment by grubersjoe** [comment]
I consider this issue fixed, please open another issue if you encounter more SSR problems.

**Comment by edwardakapo** [comment]
Same with Astro.js, was having that exact same issue until i used client:only. Great Component man you saved me days in development
